/* eslint-disable */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {};

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    AButton: typeof import('ant-design-vue')['Button']
    ADatePicker: typeof import('ant-design-vue')['DatePicker']
    AForm: typeof import('ant-design-vue')['Form']
    AFormItem: typeof import('ant-design-vue')['FormItem']
    AInput: typeof import('ant-design-vue')['Input']
    AInputNumber: typeof import('ant-design-vue')['InputNumber']
    AModal: typeof import('ant-design-vue')['Modal']
    ASelect: typeof import('ant-design-vue')['Select']
    ASelectOption: typeof import('ant-design-vue')['SelectOption']
    DialogForm: typeof import('../src/components/antd/form/dialog-form.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
  }
}
